import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/assets/styles/index.scss";
import "antd/dist/reset.css"; // ✅ 必须在最前面引入
import AntdRegistry from "./AntdRegistry"; // ✅ 引入刚才的组件

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "juejin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* ✅ 包裹 antd 的样式注册器 */}
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
